export * from "./prng.js";
export * from "./clock.js";
export * from "./sequences.js";
export * from "./world-fixture.js";
export * from "./navigation-grid.js";
export * from "./pathfinding.js";
export * from "./fog.js";
export * from "./cohort/index.js";
export * from "./create-initial-state.js";
export * from "./apply-command.js";
export * from "./advance-simulation.js";
export * from "./v2/migrate-v1-to-v2.js";
export * from "./v2/invariants.js";
export * from "./v2/create-initial-state-v2.js";
export * from "./v2/generator/index.js";
export * from "./v2/navigation-v2.js";
export * from "./v2/room-graph.js";
export * from "./v2/pathfinding-v2.js";
export * from "./v2/discovery.js";
export * from "./v2/apply-command-v2.js";
export * from "./v2/advance-simulation-v2.js";
export * from "./v2/objects/storage.js";
export * from "./v2/objects/decay.js";
export * from "./v2/objects/wear.js";
export { installationBlockReason, resolveTransformationProfileId } from "./v2/jobs/eligibility.js";
export { resolveRoomId } from "./v2/jobs/location-utils.js";
export * from "./v2/transport/cargo.js";
export { transportCapacityOf, personCarryKg, cappedContributions, coordinatedTeamKg, teamWorkFactor, usefulCarrierLimit } from "./v2/transport/capacity.js";
export { isLocationKnown, isRoomKnown, planRoute, surfaceBreakdown } from "./v2/transport/route.js";
export { destinationBlockReason, destinationNavPoint, meansBlockReason, planTransport } from "./v2/transport/plan.js";
export { settleTransportOnStop, emptyTransportState } from "./v2/transport/phases.js";
export { transportMovementFactors } from "./v2/transport/movement.js";
// S9 — Puerta C: explotación progresiva de edificios, accesos mutables y habitabilidad.
export { buildingLayerKnowledge, buildingLayerTruths, censusBuildingContent, computeHabitability, discoveryRankIndex, exploitationStageOf, layerOfWorldObject } from "./v2/exploitation/layers.js";
export { fabricOf, finishesOf, installationsOf, isBuildingTerminal, openingsOfBuilding, roomsOfBuilding, buildingIdOfOpening } from "./v2/exploitation/fabric.js";
export { buildingIdOfTarget } from "./v2/exploitation/targets.js";
export { installSiteBlockReason, installSiteOfDestination } from "./v2/exploitation/install-sites.js";
export { s9PrepareReason, s9ValidationReason, s9WorkUnits } from "./v2/exploitation/actions.js";
export { checkHardRequirements, hasKnowledge } from "./v2/jobs/eligibility.js";
