import type { ActionMethodDefinition } from "@z-world/contracts";

/**
 * Catálogo activo de métodos del motor común de resolución (WEB-002
 * §5.2/§12.2, subhito S4). Solo los siete métodos mínimos exigidos por el
 * prompt de subhitos S4-S6: reconocer, observar, inspeccionar, registrar,
 * beber, comer, descansar. El catálogo queda preparado para S7-S10
 * (recoger/transportar/reparar/desmontar/agricultura), pero esas claves no
 * se declaran aquí: una posibilidad no implementada no se muestra como
 * botón funcional (§5.2 del prompt).
 *
 * Elecciones de prioridad documentadas en `DEC-0018` (§11.6/§6.3 del
 * prompt): `recognize`/`observe`/`inspect` → `exploration_expeditions`
 * (reconocimiento, aunque inspeccionar añada diagnóstico técnico, el
 * propósito real sigue siendo exploratorio en este recorte sin trabajos de
 * reparación); `register` → `scavenge_recovery`; `drink` → `water_supply`
 * (exigido por el prompt); `eat`/`rest` → `recovery_care` (autocuidado que
 * recupera a la persona, sin crear una prioridad 35).
 */
export const ACTION_METHODS: readonly ActionMethodDefinition[] = [
  {
    key: "recognize",
    version: 1,
    labelKey: "action.recognize.label",
    descriptionKey: "action.recognize.description",
    targetKinds: ["place"],
    requiredKnowledge: [],
    revealsKnowledge: [{ facet: "exterior", state: "sighted" }],
    priority: "exploration_expeditions",
    characteristicIds: ["perception"],
    skillIds: ["alertness"],
    profile: "balanced_50_50",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }],
    difficulty: 1,
    model: "direct",
    baseWorkUnits: 5,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor"],
    phases: ["validate", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: false,
  },
  {
    key: "observe",
    version: 1,
    labelKey: "action.observe.label",
    descriptionKey: "action.observe.description",
    targetKinds: ["place", "opening", "room"],
    requiredKnowledge: [{ facet: "exterior", minimumState: "sighted" }],
    revealsKnowledge: [
      { facet: "exterior", state: "observed" },
      { facet: "accesses", state: "observed" },
    ],
    priority: "exploration_expeditions",
    characteristicIds: ["perception"],
    skillIds: ["alertness"],
    profile: "balanced_50_50",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }],
    difficulty: 3,
    model: "direct",
    baseWorkUnits: 10,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor", "operational_helper"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: true,
  },
  {
    key: "inspect",
    version: 1,
    labelKey: "action.inspect.label",
    descriptionKey: "action.inspect.description",
    targetKinds: ["building", "room", "opening"],
    requiredKnowledge: [{ facet: "structure", minimumState: "observed" }],
    revealsKnowledge: [
      { facet: "structure", state: "inspected" },
      { facet: "accesses", state: "inspected" },
    ],
    priority: "exploration_expeditions",
    characteristicIds: ["perception", "technique"],
    skillIds: ["alertness"],
    profile: "technical_30_70",
    classification: "improvisable",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 4,
    model: "b",
    baseWorkUnits: 15,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor", "reviewer"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: true,
  },
  {
    key: "register",
    version: 1,
    labelKey: "action.register.label",
    descriptionKey: "action.register.description",
    targetKinds: ["room"],
    requiredKnowledge: [{ facet: "rooms", minimumState: "observed" }],
    revealsKnowledge: [{ facet: "content", state: "inspected" }],
    priority: "scavenge_recovery",
    characteristicIds: ["perception", "dexterity"],
    skillIds: ["alertness"],
    profile: "balanced_50_50",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 4,
    model: "b",
    baseWorkUnits: 20,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 3,
    rolesAllowed: ["responsible", "primary_executor", "operational_helper"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: true,
  },
  {
    key: "drink",
    version: 1,
    labelKey: "action.drink.label",
    descriptionKey: "action.drink.description",
    targetKinds: ["resource_lot", "own_need"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "water_supply",
    characteristicIds: [],
    skillIds: [],
    profile: "balanced_50_50",
    classification: "open",
    hardRequirements: [{ kind: "requires_container_or_lot_present" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 0,
    model: "direct",
    baseWorkUnits: 2,
    unit: "liters",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 1,
    rolesAllowed: ["primary_executor"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: false,
    attentionApplies: false,
  },
  {
    key: "eat",
    version: 1,
    labelKey: "action.eat.label",
    descriptionKey: "action.eat.description",
    targetKinds: ["resource_lot", "own_need"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "recovery_care",
    characteristicIds: [],
    skillIds: [],
    profile: "balanced_50_50",
    classification: "open",
    hardRequirements: [{ kind: "requires_container_or_lot_present" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 0,
    model: "direct",
    baseWorkUnits: 1,
    unit: "portions",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 1,
    rolesAllowed: ["primary_executor"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: false,
    attentionApplies: false,
  },
  {
    key: "rest",
    version: 1,
    labelKey: "action.rest.label",
    descriptionKey: "action.rest.description",
    targetKinds: ["furniture", "room", "own_need"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "recovery_care",
    characteristicIds: [],
    skillIds: [],
    profile: "balanced_50_50",
    classification: "open",
    hardRequirements: [{ kind: "requires_rest_support" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 0,
    model: "d",
    baseWorkUnits: 240,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 1,
    rolesAllowed: ["primary_executor"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: false,
    attentionApplies: false,
  },
];

export const ACTION_METHODS_BY_KEY: ReadonlyMap<string, ActionMethodDefinition> = new Map(ACTION_METHODS.map((m) => [m.key, m]));
