import type { ActionMethodDefinition } from "@z-world/contracts";

/**
 * Catálogo activo de métodos del motor común de resolución (WEB-002
 * §5.2/§12.2, subhito S4). Solo los siete métodos mínimos exigidos por el
 * prompt de subhitos S4-S6: reconocer, observar, inspeccionar, registrar,
 * beber, comer, descansar. El catálogo queda preparado para S7-S10
 * (recoger/transportar/reparar/desmontar/agricultura), pero esas claves no
 * se declaran aquí: una posibilidad no implementada no se muestra como
 * botón funcional (§5.2 del prompt).
 *
 * Elecciones de prioridad documentadas en `DEC-0018` (§11.6/§6.3 del
 * prompt): `recognize`/`observe`/`inspect` → `exploration_expeditions`
 * (reconocimiento, aunque inspeccionar añada diagnóstico técnico, el
 * propósito real sigue siendo exploratorio en este recorte sin trabajos de
 * reparación); `register` → `scavenge_recovery`; `drink` → `water_supply`
 * (exigido por el prompt); `eat`/`rest` → `recovery_care` (autocuidado que
 * recupera a la persona, sin crear una prioridad 35).
 */
export const ACTION_METHODS: readonly ActionMethodDefinition[] = [
  {
    key: "recognize",
    version: 1,
    labelKey: "action.recognize.label",
    descriptionKey: "action.recognize.description",
    targetKinds: ["place"],
    requiredKnowledge: [],
    revealsKnowledge: [{ facet: "exterior", state: "sighted" }],
    priority: "exploration_expeditions",
    characteristicIds: ["perception"],
    skillIds: ["alertness"],
    profile: "balanced_50_50",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }],
    difficulty: 1,
    model: "direct",
    baseWorkUnits: 5,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor"],
    phases: ["validate", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: false,
    irreversible: false,
  },
  {
    key: "observe",
    version: 1,
    labelKey: "action.observe.label",
    descriptionKey: "action.observe.description",
    targetKinds: ["place", "opening", "room"],
    requiredKnowledge: [{ facet: "exterior", minimumState: "sighted" }],
    revealsKnowledge: [
      { facet: "exterior", state: "observed" },
      { facet: "accesses", state: "observed" },
    ],
    priority: "exploration_expeditions",
    characteristicIds: ["perception"],
    skillIds: ["alertness"],
    profile: "balanced_50_50",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }],
    difficulty: 3,
    model: "direct",
    baseWorkUnits: 10,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor", "operational_helper"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: true,
    irreversible: false,
  },
  {
    key: "inspect",
    version: 1,
    labelKey: "action.inspect.label",
    descriptionKey: "action.inspect.description",
    targetKinds: ["building", "room", "opening"],
    requiredKnowledge: [{ facet: "structure", minimumState: "observed" }],
    revealsKnowledge: [
      { facet: "structure", state: "inspected" },
      { facet: "accesses", state: "inspected" },
    ],
    priority: "exploration_expeditions",
    characteristicIds: ["perception", "technique"],
    skillIds: ["alertness"],
    profile: "technical_30_70",
    classification: "improvisable",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 4,
    model: "b",
    baseWorkUnits: 15,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor", "reviewer"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: true,
    irreversible: false,
  },
  {
    key: "register",
    version: 1,
    labelKey: "action.register.label",
    descriptionKey: "action.register.description",
    targetKinds: ["room"],
    requiredKnowledge: [{ facet: "rooms", minimumState: "observed" }],
    revealsKnowledge: [{ facet: "content", state: "inspected" }],
    priority: "scavenge_recovery",
    characteristicIds: ["perception", "dexterity"],
    skillIds: ["alertness"],
    profile: "balanced_50_50",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 4,
    model: "b",
    baseWorkUnits: 20,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 3,
    rolesAllowed: ["responsible", "primary_executor", "operational_helper"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: true,
    irreversible: false,
  },
  {
    key: "drink",
    version: 1,
    labelKey: "action.drink.label",
    descriptionKey: "action.drink.description",
    targetKinds: ["resource_lot", "own_need"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "water_supply",
    characteristicIds: [],
    skillIds: [],
    profile: "balanced_50_50",
    classification: "open",
    hardRequirements: [{ kind: "requires_container_or_lot_present" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 0,
    model: "direct",
    baseWorkUnits: 2,
    unit: "liters",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 1,
    rolesAllowed: ["primary_executor"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: false,
    attentionApplies: false,
    irreversible: false,
  },
  {
    key: "eat",
    version: 1,
    labelKey: "action.eat.label",
    descriptionKey: "action.eat.description",
    targetKinds: ["resource_lot", "own_need"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "recovery_care",
    characteristicIds: [],
    skillIds: [],
    profile: "balanced_50_50",
    classification: "open",
    hardRequirements: [{ kind: "requires_container_or_lot_present" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 0,
    model: "direct",
    baseWorkUnits: 1,
    unit: "portions",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 1,
    rolesAllowed: ["primary_executor"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: false,
    attentionApplies: false,
    irreversible: false,
  },
  {
    key: "rest",
    version: 1,
    labelKey: "action.rest.label",
    descriptionKey: "action.rest.description",
    targetKinds: ["furniture", "room", "own_need"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "recovery_care",
    characteristicIds: [],
    skillIds: [],
    profile: "balanced_50_50",
    classification: "open",
    hardRequirements: [{ kind: "requires_rest_support" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 0,
    model: "d",
    baseWorkUnits: 240,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 1,
    rolesAllowed: ["primary_executor"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: false,
    attentionApplies: false,
    irreversible: false,
  },
];

/**
 * Métodos S7 (`DEC-0019`, §15/§16 del prompt S7-S9): recoger, almacenar,
 * retirar de almacenamiento, reparar, desmontar selectivo y desguace
 * destructivo. Comparten la misma tubería directa/D/B y la misma entidad
 * `Job` que S4-S6; el desmontaje y el desguace declaran `irreversible` y
 * exigen `requires_irreversible_confirmation` (§16.4).
 */
export const OBJECT_ACTION_METHODS: readonly ActionMethodDefinition[] = [
  {
    key: "collect",
    version: 2,
    labelKey: "action.collect.label",
    descriptionKey: "action.collect.description",
    // v2 (S7): también recoge lotes sueltos en una estancia (p. ej. productos de un desmontaje).
    targetKinds: ["world_object", "resource_lot", "furniture"],
    requiredKnowledge: [{ facet: "content", minimumState: "inspected" }],
    revealsKnowledge: [],
    priority: "scavenge_recovery",
    characteristicIds: ["dexterity"],
    skillIds: [],
    profile: "physical_70_30",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 1,
    model: "direct",
    baseWorkUnits: 3,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor"],
    phases: ["validate", "travel", "collect", "record_result"],
    paceApplies: true,
    attentionApplies: false,
    irreversible: false,
  },
  {
    // v2 (S7): el blanco es el `Container` real de destino (CAT-005 §4.4) y
    // `Job.storageItem` el objeto/lote que se guarda. La v1 declaraba
    // `world_object`/`furniture` como blanco pero nunca llegó a ejecutarse.
    key: "store",
    version: 2,
    labelKey: "action.store.label",
    descriptionKey: "action.store.description",
    targetKinds: ["container"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "logistics",
    characteristicIds: ["dexterity"],
    skillIds: [],
    profile: "physical_70_30",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_storage_container" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 1,
    model: "direct",
    baseWorkUnits: 3,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor"],
    phases: ["validate", "travel", "deliver", "record_result"],
    paceApplies: true,
    attentionApplies: false,
    irreversible: false,
  },
  {
    key: "retrieve_from_storage",
    version: 2,
    labelKey: "action.retrieve_from_storage.label",
    descriptionKey: "action.retrieve_from_storage.description",
    targetKinds: ["container"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "logistics",
    characteristicIds: ["dexterity"],
    skillIds: [],
    profile: "physical_70_30",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_storage_container" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 1,
    model: "direct",
    baseWorkUnits: 3,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor"],
    phases: ["validate", "travel", "collect", "record_result"],
    paceApplies: true,
    attentionApplies: false,
    irreversible: false,
  },
  {
    key: "repair",
    version: 2,
    labelKey: "action.repair.label",
    descriptionKey: "action.repair.description",
    // v2 (S7): la carretilla/carro (`TransportMeans`) es un objeto completo reparable/desmontable.
    targetKinds: ["world_object", "furniture", "transport_means"],
    requiredKnowledge: [{ facet: "content", minimumState: "inspected" }],
    revealsKnowledge: [],
    priority: "repair",
    characteristicIds: ["technique"],
    skillIds: ["mechanics"],
    profile: "technical_30_70",
    classification: "guided",
    hardRequirements: [
      { kind: "known_target" },
      { kind: "requires_shared_location_or_reach" },
      { kind: "requires_transformation_profile" },
      { kind: "requires_concrete_materials" },
    ],
    difficulty: 5,
    model: "b",
    baseWorkUnits: 45,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor", "operational_helper"],
    phases: ["validate", "travel", "prepare", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: true,
    irreversible: false,
  },
  {
    key: "disassemble_selective",
    version: 2,
    labelKey: "action.disassemble_selective.label",
    descriptionKey: "action.disassemble_selective.description",
    // v2 (S7): la carretilla/carro (`TransportMeans`) es un objeto completo reparable/desmontable.
    targetKinds: ["world_object", "furniture", "transport_means"],
    requiredKnowledge: [{ facet: "content", minimumState: "inspected" }],
    revealsKnowledge: [],
    priority: "dismantling_recycling",
    characteristicIds: ["technique"],
    skillIds: ["mechanics"],
    profile: "technical_30_70",
    classification: "guided",
    hardRequirements: [
      { kind: "known_target" },
      { kind: "requires_shared_location_or_reach" },
      { kind: "requires_transformation_profile" },
      { kind: "requires_irreversible_confirmation" },
    ],
    difficulty: 6,
    model: "b",
    baseWorkUnits: 90,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor", "operational_helper"],
    phases: ["validate", "travel", "prepare", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: true,
    irreversible: true,
  },
  {
    key: "disassemble_destructive",
    version: 2,
    labelKey: "action.disassemble_destructive.label",
    descriptionKey: "action.disassemble_destructive.description",
    // v2 (S7): la carretilla/carro (`TransportMeans`) es un objeto completo reparable/desmontable.
    targetKinds: ["world_object", "furniture", "transport_means"],
    requiredKnowledge: [{ facet: "content", minimumState: "inspected" }],
    revealsKnowledge: [],
    priority: "dismantling_recycling",
    characteristicIds: ["strength"],
    skillIds: ["mechanics"],
    profile: "physical_70_30",
    classification: "open",
    hardRequirements: [
      { kind: "known_target" },
      { kind: "requires_shared_location_or_reach" },
      { kind: "requires_transformation_profile" },
      { kind: "requires_irreversible_confirmation" },
    ],
    difficulty: 3,
    model: "d",
    baseWorkUnits: 30,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor", "operational_helper"],
    phases: ["validate", "travel", "prepare", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: false,
    irreversible: true,
  },
  {
    // Bomba de agua (CAT-005 §3.2): probar/diagnosticar revela su estado
    // funcional real y las funciones inactivas con su causa. Prioridad
    // `repair`: el diagnóstico forma parte de la cadena de reparación.
    key: "test_installation",
    version: 1,
    labelKey: "action.test_installation.label",
    descriptionKey: "action.test_installation.description",
    targetKinds: ["world_object"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "repair",
    characteristicIds: ["technique"],
    skillIds: ["mechanics"],
    profile: "technical_30_70",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 2,
    model: "d",
    baseWorkUnits: 10,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor", "operational_helper"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: false,
    irreversible: false,
  },
  {
    // Extraer agua con una bomba funcional conectada a su fuente real: produce
    // un lote de agua localizado junto a la bomba y la desgasta de forma
    // determinista (avería causal por uso, nunca por azar).
    key: "draw_water",
    version: 1,
    labelKey: "action.draw_water.label",
    descriptionKey: "action.draw_water.description",
    targetKinds: ["world_object"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "water_supply",
    characteristicIds: ["strength"],
    skillIds: [],
    profile: "physical_70_30",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_shared_location_or_reach" }, { kind: "requires_functional_installation" }],
    difficulty: 1,
    model: "d",
    baseWorkUnits: 10,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor", "operational_helper"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: false,
    irreversible: false,
  },
  {
    // S8 (Puerta B): traslado físico con uno de los cinco métodos activos
    // (SET-010 §3.2). Mismo `Job`, mismas fases comunes y mismas reservas
    // que el resto del catálogo: el paso logístico fino (recuperar medio,
    // cargar, recorrer, atravesar accesos, descargar, estacionar) vive en
    // `Job.transport` y lo ejecuta `advance-jobs.ts` con el motor único de
    // `simulation-core/src/v2/transport`. Prioridad `logistics` (mover/
    // almacenar, §9 del prompt S7-S9).
    key: "transport",
    version: 1,
    labelKey: "action.transport.label",
    descriptionKey: "action.transport.description",
    targetKinds: ["world_object", "resource_lot", "furniture"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "logistics",
    characteristicIds: ["strength", "endurance"],
    skillIds: [],
    profile: "physical_70_30",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }],
    difficulty: 1,
    model: "direct",
    baseWorkUnits: 0,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 4,
    rolesAllowed: ["responsible", "primary_executor", "operational_helper", "logistics_support"],
    phases: ["validate", "reserve", "prepare", "collect", "transport", "deliver", "close", "record_result"],
    paceApplies: true,
    attentionApplies: true,
    irreversible: false,
  },
];

/** Litros que produce una extracción completa de `draw_water` (S7, provisional y documentado en `docs/STATUS.md`). */
export const DRAW_WATER_LITERS_PER_JOB = 10;

/** Métodos S7 cuyo blanco (y, en almacenamiento, el elemento movido) se reserva en exclusiva (S7 §7.7/§9: "reservas impiden doble uso"). */
export const EXCLUSIVE_TARGET_ACTION_KEYS: ReadonlySet<string> = new Set([
  "collect",
  "store",
  "retrieve_from_storage",
  "repair",
  "disassemble_selective",
  "disassemble_destructive",
  "test_installation",
  "draw_water",
  "transport",
]);

export const ACTION_METHODS_BY_KEY: ReadonlyMap<string, ActionMethodDefinition> = new Map(
  [...ACTION_METHODS, ...OBJECT_ACTION_METHODS].map((m) => [m.key, m]),
);
