import type { ActionMethodDefinition } from "@z-world/contracts";

/**
 * Catálogo activo de métodos del motor común de resolución (WEB-002
 * §5.2/§12.2, subhito S4). Solo los siete métodos mínimos exigidos por el
 * prompt de subhitos S4-S6: reconocer, observar, inspeccionar, registrar,
 * beber, comer, descansar. El catálogo queda preparado para S7-S10
 * (recoger/transportar/reparar/desmontar/agricultura), pero esas claves no
 * se declaran aquí: una posibilidad no implementada no se muestra como
 * botón funcional (§5.2 del prompt).
 *
 * Elecciones de prioridad documentadas en `DEC-0018` (§11.6/§6.3 del
 * prompt): `recognize`/`observe`/`inspect` → `exploration_expeditions`
 * (reconocimiento, aunque inspeccionar añada diagnóstico técnico, el
 * propósito real sigue siendo exploratorio en este recorte sin trabajos de
 * reparación); `register` → `scavenge_recovery`; `drink` → `water_supply`
 * (exigido por el prompt); `eat`/`rest` → `recovery_care` (autocuidado que
 * recupera a la persona, sin crear una prioridad 35).
 */
export const ACTION_METHODS: readonly ActionMethodDefinition[] = [
  {
    key: "recognize",
    version: 1,
    labelKey: "action.recognize.label",
    descriptionKey: "action.recognize.description",
    targetKinds: ["place"],
    requiredKnowledge: [],
    revealsKnowledge: [{ facet: "exterior", state: "sighted" }],
    priority: "exploration_expeditions",
    characteristicIds: ["perception"],
    skillIds: ["alertness"],
    profile: "balanced_50_50",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }],
    difficulty: 1,
    model: "direct",
    baseWorkUnits: 5,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor"],
    phases: ["validate", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: false,
    irreversible: false,
  },
  {
    key: "observe",
    version: 1,
    labelKey: "action.observe.label",
    descriptionKey: "action.observe.description",
    targetKinds: ["place", "opening", "room"],
    requiredKnowledge: [{ facet: "exterior", minimumState: "sighted" }],
    revealsKnowledge: [
      { facet: "exterior", state: "observed" },
      { facet: "accesses", state: "observed" },
    ],
    priority: "exploration_expeditions",
    characteristicIds: ["perception"],
    skillIds: ["alertness"],
    profile: "balanced_50_50",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }],
    difficulty: 3,
    model: "direct",
    baseWorkUnits: 10,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor", "operational_helper"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: true,
    irreversible: false,
  },
  {
    key: "inspect",
    version: 1,
    labelKey: "action.inspect.label",
    descriptionKey: "action.inspect.description",
    targetKinds: ["building", "room", "opening"],
    requiredKnowledge: [{ facet: "structure", minimumState: "observed" }],
    revealsKnowledge: [
      { facet: "structure", state: "inspected" },
      { facet: "accesses", state: "inspected" },
    ],
    priority: "exploration_expeditions",
    characteristicIds: ["perception", "technique"],
    skillIds: ["alertness"],
    profile: "technical_30_70",
    classification: "improvisable",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 4,
    model: "b",
    baseWorkUnits: 15,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor", "reviewer"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: true,
    irreversible: false,
  },
  {
    key: "register",
    version: 1,
    labelKey: "action.register.label",
    descriptionKey: "action.register.description",
    targetKinds: ["room"],
    requiredKnowledge: [{ facet: "rooms", minimumState: "observed" }],
    revealsKnowledge: [{ facet: "content", state: "inspected" }],
    priority: "scavenge_recovery",
    characteristicIds: ["perception", "dexterity"],
    skillIds: ["alertness"],
    profile: "balanced_50_50",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 4,
    model: "b",
    baseWorkUnits: 20,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 3,
    rolesAllowed: ["responsible", "primary_executor", "operational_helper"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: true,
    irreversible: false,
  },
  {
    key: "drink",
    version: 1,
    labelKey: "action.drink.label",
    descriptionKey: "action.drink.description",
    targetKinds: ["resource_lot", "own_need"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "water_supply",
    characteristicIds: [],
    skillIds: [],
    profile: "balanced_50_50",
    classification: "open",
    hardRequirements: [{ kind: "requires_container_or_lot_present" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 0,
    model: "direct",
    baseWorkUnits: 2,
    unit: "liters",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 1,
    rolesAllowed: ["primary_executor"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: false,
    attentionApplies: false,
    irreversible: false,
  },
  {
    key: "eat",
    version: 1,
    labelKey: "action.eat.label",
    descriptionKey: "action.eat.description",
    targetKinds: ["resource_lot", "own_need"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "recovery_care",
    characteristicIds: [],
    skillIds: [],
    profile: "balanced_50_50",
    classification: "open",
    hardRequirements: [{ kind: "requires_container_or_lot_present" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 0,
    model: "direct",
    baseWorkUnits: 1,
    unit: "portions",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 1,
    rolesAllowed: ["primary_executor"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: false,
    attentionApplies: false,
    irreversible: false,
  },
  {
    key: "rest",
    version: 1,
    labelKey: "action.rest.label",
    descriptionKey: "action.rest.description",
    targetKinds: ["furniture", "room", "own_need"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "recovery_care",
    characteristicIds: [],
    skillIds: [],
    profile: "balanced_50_50",
    classification: "open",
    hardRequirements: [{ kind: "requires_rest_support" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 0,
    model: "d",
    baseWorkUnits: 240,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 1,
    rolesAllowed: ["primary_executor"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: false,
    attentionApplies: false,
    irreversible: false,
  },
];

/**
 * Métodos S7 (`DEC-0019`, §15/§16 del prompt S7-S9): recoger, almacenar,
 * retirar de almacenamiento, reparar, desmontar selectivo y desguace
 * destructivo. Comparten la misma tubería directa/D/B y la misma entidad
 * `Job` que S4-S6; el desmontaje y el desguace declaran `irreversible` y
 * exigen `requires_irreversible_confirmation` (§16.4).
 */
export const OBJECT_ACTION_METHODS: readonly ActionMethodDefinition[] = [
  {
    key: "collect",
    version: 2,
    labelKey: "action.collect.label",
    descriptionKey: "action.collect.description",
    // v2 (S7): también recoge lotes sueltos en una estancia (p. ej. productos de un desmontaje).
    targetKinds: ["world_object", "resource_lot", "furniture"],
    requiredKnowledge: [{ facet: "content", minimumState: "inspected" }],
    revealsKnowledge: [],
    priority: "scavenge_recovery",
    characteristicIds: ["dexterity"],
    skillIds: [],
    profile: "physical_70_30",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 1,
    model: "direct",
    baseWorkUnits: 3,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor"],
    phases: ["validate", "travel", "collect", "record_result"],
    paceApplies: true,
    attentionApplies: false,
    irreversible: false,
  },
  {
    // v2 (S7): el blanco es el `Container` real de destino (CAT-005 §4.4) y
    // `Job.storageItem` el objeto/lote que se guarda. La v1 declaraba
    // `world_object`/`furniture` como blanco pero nunca llegó a ejecutarse.
    key: "store",
    version: 2,
    labelKey: "action.store.label",
    descriptionKey: "action.store.description",
    targetKinds: ["container"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "logistics",
    characteristicIds: ["dexterity"],
    skillIds: [],
    profile: "physical_70_30",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_storage_container" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 1,
    model: "direct",
    baseWorkUnits: 3,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor"],
    phases: ["validate", "travel", "deliver", "record_result"],
    paceApplies: true,
    attentionApplies: false,
    irreversible: false,
  },
  {
    key: "retrieve_from_storage",
    version: 2,
    labelKey: "action.retrieve_from_storage.label",
    descriptionKey: "action.retrieve_from_storage.description",
    targetKinds: ["container"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "logistics",
    characteristicIds: ["dexterity"],
    skillIds: [],
    profile: "physical_70_30",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_storage_container" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 1,
    model: "direct",
    baseWorkUnits: 3,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor"],
    phases: ["validate", "travel", "collect", "record_result"],
    paceApplies: true,
    attentionApplies: false,
    irreversible: false,
  },
  {
    key: "repair",
    version: 2,
    labelKey: "action.repair.label",
    descriptionKey: "action.repair.description",
    // v2 (S7): la carretilla/carro (`TransportMeans`) es un objeto completo reparable/desmontable.
    targetKinds: ["world_object", "furniture", "transport_means"],
    requiredKnowledge: [{ facet: "content", minimumState: "inspected" }],
    revealsKnowledge: [],
    priority: "repair",
    characteristicIds: ["technique"],
    skillIds: ["mechanics"],
    profile: "technical_30_70",
    classification: "guided",
    hardRequirements: [
      { kind: "known_target" },
      { kind: "requires_shared_location_or_reach" },
      { kind: "requires_transformation_profile" },
      { kind: "requires_concrete_materials" },
    ],
    difficulty: 5,
    model: "b",
    baseWorkUnits: 45,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor", "operational_helper"],
    phases: ["validate", "travel", "prepare", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: true,
    irreversible: false,
  },
  {
    key: "disassemble_selective",
    version: 2,
    labelKey: "action.disassemble_selective.label",
    descriptionKey: "action.disassemble_selective.description",
    // v2 (S7): la carretilla/carro (`TransportMeans`) es un objeto completo reparable/desmontable.
    targetKinds: ["world_object", "furniture", "transport_means"],
    requiredKnowledge: [{ facet: "content", minimumState: "inspected" }],
    revealsKnowledge: [],
    priority: "dismantling_recycling",
    characteristicIds: ["technique"],
    skillIds: ["mechanics"],
    profile: "technical_30_70",
    classification: "guided",
    hardRequirements: [
      { kind: "known_target" },
      { kind: "requires_shared_location_or_reach" },
      { kind: "requires_transformation_profile" },
      { kind: "requires_irreversible_confirmation" },
    ],
    difficulty: 6,
    model: "b",
    baseWorkUnits: 90,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor", "operational_helper"],
    phases: ["validate", "travel", "prepare", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: true,
    irreversible: true,
  },
  {
    key: "disassemble_destructive",
    version: 2,
    labelKey: "action.disassemble_destructive.label",
    descriptionKey: "action.disassemble_destructive.description",
    // v2 (S7): la carretilla/carro (`TransportMeans`) es un objeto completo reparable/desmontable.
    targetKinds: ["world_object", "furniture", "transport_means"],
    requiredKnowledge: [{ facet: "content", minimumState: "inspected" }],
    revealsKnowledge: [],
    priority: "dismantling_recycling",
    characteristicIds: ["strength"],
    skillIds: ["mechanics"],
    profile: "physical_70_30",
    classification: "open",
    hardRequirements: [
      { kind: "known_target" },
      { kind: "requires_shared_location_or_reach" },
      { kind: "requires_transformation_profile" },
      { kind: "requires_irreversible_confirmation" },
    ],
    difficulty: 3,
    model: "d",
    baseWorkUnits: 30,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor", "operational_helper"],
    phases: ["validate", "travel", "prepare", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: false,
    irreversible: true,
  },
  {
    // Bomba de agua (CAT-005 §3.2): probar/diagnosticar revela su estado
    // funcional real y las funciones inactivas con su causa. Prioridad
    // `repair`: el diagnóstico forma parte de la cadena de reparación.
    key: "test_installation",
    version: 1,
    labelKey: "action.test_installation.label",
    descriptionKey: "action.test_installation.description",
    targetKinds: ["world_object"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "repair",
    characteristicIds: ["technique"],
    skillIds: ["mechanics"],
    profile: "technical_30_70",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 2,
    model: "d",
    baseWorkUnits: 10,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor", "operational_helper"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: false,
    irreversible: false,
  },
  {
    // Extraer agua con una bomba funcional conectada a su fuente real: produce
    // un lote de agua localizado junto a la bomba y la desgasta de forma
    // determinista (avería causal por uso, nunca por azar).
    key: "draw_water",
    version: 1,
    labelKey: "action.draw_water.label",
    descriptionKey: "action.draw_water.description",
    targetKinds: ["world_object"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "water_supply",
    characteristicIds: ["strength"],
    skillIds: [],
    profile: "physical_70_30",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_shared_location_or_reach" }, { kind: "requires_functional_installation" }],
    difficulty: 1,
    model: "d",
    baseWorkUnits: 10,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor", "operational_helper"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: false,
    irreversible: false,
  },
  {
    // S8 (Puerta B): traslado físico con uno de los cinco métodos activos
    // (SET-010 §3.2). Mismo `Job`, mismas fases comunes y mismas reservas
    // que el resto del catálogo: el paso logístico fino (recuperar medio,
    // cargar, recorrer, atravesar accesos, descargar, estacionar) vive en
    // `Job.transport` y lo ejecuta `advance-jobs.ts` con el motor único de
    // `simulation-core/src/v2/transport`. Prioridad `logistics` (mover/
    // almacenar, §9 del prompt S7-S9).
    key: "transport",
    version: 1,
    labelKey: "action.transport.label",
    descriptionKey: "action.transport.description",
    targetKinds: ["world_object", "resource_lot", "furniture"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "logistics",
    characteristicIds: ["strength", "endurance"],
    skillIds: [],
    profile: "physical_70_30",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }],
    difficulty: 1,
    model: "direct",
    baseWorkUnits: 0,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 4,
    rolesAllowed: ["responsible", "primary_executor", "operational_helper", "logistics_support"],
    phases: ["validate", "reserve", "prepare", "collect", "transport", "deliver", "close", "record_result"],
    paceApplies: true,
    attentionApplies: true,
    irreversible: false,
  },
];

/**
 * Métodos S9 — Puerta C (`DEC-0019`, SET-007, WLD-011 §3.4-§3.5, §8 del
 * prompt S7-S9). Misma entidad `Job`, mismas fases comunes y mismo motor
 * directo/D/B (`d_then_b`: trabajo con duración real y un único episodio B
 * al terminar). Cada método es una acción distinta con requisitos, tiempos y
 * consecuencias propios: registrar ≠ recuperar entero ≠ desmontar objeto ≠
 * desmontar instalación ≠ retirar acabado ≠ desmantelar estructura ≠
 * demoler. Los que destruyen de forma permanente declaran `irreversible` y
 * exigen confirmación informada. Las duraciones concretas (puerta frente a
 * portón, m² de huella, receta de la instalación) las fija el catálogo
 * versionado `building-exploitation.ts` al crear el trabajo; aquí
 * `baseWorkUnits` es solo el valor de referencia.
 */
const ACCESS_PHASES = ["validate", "travel", "execute", "record_result"] as const;
const PREPARED_PHASES = ["validate", "travel", "prepare", "execute", "record_result"] as const;
const ACCESS_ROLES = ["responsible", "primary_executor", "operational_helper"] as const;

function accessMethod(input: Pick<ActionMethodDefinition, "key" | "priority" | "model" | "baseWorkUnits" | "difficulty" | "characteristicIds" | "skillIds" | "profile"> & Partial<ActionMethodDefinition>): ActionMethodDefinition {
  return {
    version: 1,
    labelKey: `action.${input.key}.label`,
    descriptionKey: `action.${input.key}.description`,
    targetKinds: ["opening"],
    requiredKnowledge: [{ facet: "accesses", minimumState: "observed" }],
    revealsKnowledge: [],
    classification: "open",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_building_standing" }, { kind: "requires_installed_closure" }],
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: [...ACCESS_ROLES],
    phases: [...ACCESS_PHASES],
    paceApplies: true,
    attentionApplies: false,
    irreversible: false,
    ...input,
  };
}

export const EXPLOITATION_ACTION_METHODS: readonly ActionMethodDefinition[] = [
  // --- Accesos (WLD-011 §3.4): abertura, cierre y modificación siguen siendo tres identidades separadas.
  accessMethod({ key: "open_closure", priority: "logistics", model: "direct", baseWorkUnits: 1, difficulty: 0, characteristicIds: [], skillIds: [], profile: "balanced_50_50" }),
  accessMethod({ key: "close_closure", priority: "logistics", model: "direct", baseWorkUnits: 1, difficulty: 0, characteristicIds: [], skillIds: [], profile: "balanced_50_50" }),
  accessMethod({ key: "lock_closure", priority: "construction_fortification", model: "direct", baseWorkUnits: 2, difficulty: 0, characteristicIds: [], skillIds: [], profile: "balanced_50_50" }),
  accessMethod({ key: "unlock_closure", priority: "construction_fortification", model: "direct", baseWorkUnits: 2, difficulty: 0, characteristicIds: [], skillIds: [], profile: "balanced_50_50" }),
  // Forzar: trabajo real y un episodio B (fuerza + cerrajería); rompe el mecanismo y hace ruido.
  accessMethod({ key: "force_closure", priority: "scavenge_recovery", model: "d_then_b", baseWorkUnits: 10, difficulty: 3, characteristicIds: ["strength", "technique"], skillIds: ["locksmithing"], profile: "physical_70_30", classification: "improvisable" }),
  accessMethod({
    key: "clear_obstruction",
    priority: "logistics",
    model: "d",
    baseWorkUnits: 20,
    difficulty: 1,
    characteristicIds: ["strength"],
    skillIds: [],
    profile: "physical_70_30",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_building_standing" }, { kind: "requires_obstruction" }],
  }),
  accessMethod({
    key: "barricade_opening",
    priority: "construction_fortification",
    model: "d",
    baseWorkUnits: 30,
    difficulty: 2,
    characteristicIds: ["strength", "dexterity"],
    skillIds: ["carpentry"],
    profile: "physical_70_30",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_building_standing" }, { kind: "requires_concrete_materials" }],
    phases: [...PREPARED_PHASES],
  }),
  // Tapiar: sustituye funcionalmente la abertura por un tramo cerrado con material concreto (WLD-011 §3.5).
  accessMethod({
    key: "board_up_opening",
    priority: "construction_fortification",
    model: "d",
    baseWorkUnits: 90,
    difficulty: 3,
    characteristicIds: ["strength", "dexterity"],
    skillIds: ["carpentry", "construction"],
    profile: "physical_70_30",
    classification: "improvisable",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_building_standing" }, { kind: "requires_concrete_materials" }],
    phases: [...PREPARED_PHASES],
  }),
  accessMethod({
    key: "reinforce_closure",
    priority: "construction_fortification",
    model: "d",
    baseWorkUnits: 25,
    difficulty: 2,
    characteristicIds: ["dexterity", "strength"],
    skillIds: ["carpentry"],
    profile: "physical_70_30",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_building_standing" }, { kind: "requires_installed_closure" }, { kind: "requires_concrete_materials" }],
    phases: [...PREPARED_PHASES],
  }),
  accessMethod({
    key: "repair_closure",
    priority: "repair",
    model: "d_then_b",
    baseWorkUnits: 40,
    // Calibrado con la cohorte real (carpintería/cerrajería 0-3): una persona hábil repara una puerta con buena probabilidad; sin mano, suele quedar a medias.
    difficulty: 2,
    characteristicIds: ["technique", "dexterity"],
    skillIds: ["carpentry", "locksmithing"],
    profile: "balanced_50_50",
    classification: "guided",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_building_standing" }, { kind: "requires_installed_closure" }, { kind: "requires_concrete_materials" }],
    phases: [...PREPARED_PHASES],
  }),
  // Retirar preservando: el cierre pasa a ser un objeto localizado y la abertura sigue existiendo (y transitable).
  accessMethod({ key: "remove_closure", priority: "dismantling_recycling", model: "d", baseWorkUnits: 30, difficulty: 3, characteristicIds: ["technique", "strength"], skillIds: ["carpentry"], profile: "balanced_50_50", recommendedParticipants: 2, phases: [...PREPARED_PHASES] }),
  // Destruir: rápido y ruidoso; deja paso, madera de desecho y ningún cierre recuperable (irreversible).
  accessMethod({ key: "destroy_closure", priority: "dismantling_recycling", model: "d", baseWorkUnits: 10, difficulty: 1, characteristicIds: ["strength"], skillIds: [], profile: "physical_70_30", irreversible: true, hardRequirements: [{ kind: "known_target" }, { kind: "requires_building_standing" }, { kind: "requires_installed_closure" }, { kind: "requires_irreversible_confirmation" }], phases: [...PREPARED_PHASES] }),
  // Instalar: una puerta/portón recuperado en una abertura sin cierre, o la bomba en una fuente `ENV-01`.
  accessMethod({
    key: "install",
    priority: "construction_fortification",
    model: "d",
    baseWorkUnits: 45,
    difficulty: 3,
    characteristicIds: ["technique", "strength"],
    skillIds: ["carpentry", "mechanics"],
    profile: "technical_30_70",
    classification: "guided",
    targetKinds: ["opening", "place"],
    requiredKnowledge: [],
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_building_standing" }],
    recommendedParticipants: 2,
    phases: [...PREPARED_PHASES],
  }),

  // --- Capa 3: instalaciones (registro técnico, desconexión, desmontaje; bomba entera).
  {
    key: "survey_installations",
    version: 1,
    labelKey: "action.survey_installations.label",
    descriptionKey: "action.survey_installations.description",
    targetKinds: ["building"],
    requiredKnowledge: [{ facet: "structure", minimumState: "observed" }],
    revealsKnowledge: [],
    priority: "scavenge_recovery",
    characteristicIds: ["technique", "perception"],
    skillIds: ["electricity", "mechanics"],
    profile: "technical_30_70",
    classification: "guided",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_building_standing" }],
    difficulty: 5,
    model: "d_then_b",
    baseWorkUnits: 30,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: ["responsible", "primary_executor", "reviewer"],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: true,
    irreversible: false,
  },
  {
    key: "disconnect_installation",
    version: 1,
    labelKey: "action.disconnect_installation.label",
    descriptionKey: "action.disconnect_installation.description",
    targetKinds: ["building_installation"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "dismantling_recycling",
    characteristicIds: ["technique"],
    skillIds: ["electricity"],
    profile: "technical_30_70",
    classification: "guided",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_building_standing" }, { kind: "requires_known_installation" }],
    difficulty: 3,
    model: "d",
    baseWorkUnits: 20,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: [...ACCESS_ROLES],
    phases: ["validate", "travel", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: false,
    irreversible: false,
  },
  {
    key: "dismantle_installation",
    version: 1,
    labelKey: "action.dismantle_installation.label",
    descriptionKey: "action.dismantle_installation.description",
    targetKinds: ["building_installation"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "dismantling_recycling",
    characteristicIds: ["technique", "dexterity"],
    skillIds: ["electricity", "mechanics"],
    profile: "technical_30_70",
    classification: "guided",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_building_standing" }, { kind: "requires_known_installation" }, { kind: "requires_irreversible_confirmation" }],
    difficulty: 5,
    model: "d_then_b",
    baseWorkUnits: 60,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 2,
    maxParticipants: 2,
    rolesAllowed: [...ACCESS_ROLES],
    phases: [...PREPARED_PHASES],
    paceApplies: true,
    attentionApplies: true,
    irreversible: true,
  },
  {
    // «Desinstalar» la bomba entera (frente a desmontarla, S7): desconecta y libera anclajes; queda un objeto completo trasladable y reinstalable.
    key: "uninstall_installation",
    version: 1,
    labelKey: "action.uninstall_installation.label",
    descriptionKey: "action.uninstall_installation.description",
    targetKinds: ["world_object"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "water_supply",
    characteristicIds: ["technique", "strength"],
    skillIds: ["mechanics"],
    profile: "technical_30_70",
    classification: "guided",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_shared_location_or_reach" }],
    difficulty: 3,
    model: "d",
    baseWorkUnits: 60,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 2,
    maxParticipants: 2,
    rolesAllowed: [...ACCESS_ROLES],
    phases: [...PREPARED_PHASES],
    paceApplies: true,
    attentionApplies: false,
    irreversible: false,
  },

  // --- Capa 4: acabados (retirada cuidadosa que reduce la habitabilidad para siempre).
  {
    key: "strip_finish",
    version: 1,
    labelKey: "action.strip_finish.label",
    descriptionKey: "action.strip_finish.description",
    targetKinds: ["building_finish"],
    requiredKnowledge: [],
    revealsKnowledge: [],
    priority: "dismantling_recycling",
    characteristicIds: ["technique", "dexterity"],
    skillIds: ["carpentry", "construction"],
    profile: "technical_30_70",
    classification: "improvisable",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_building_standing" }, { kind: "requires_irreversible_confirmation" }],
    difficulty: 3,
    model: "d",
    baseWorkUnits: 45,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 2,
    rolesAllowed: [...ACCESS_ROLES],
    phases: [...PREPARED_PHASES],
    paceApplies: true,
    attentionApplies: true,
    irreversible: true,
  },

  // --- Capa 5: estructura (tercera vida): desmantelar por etapas o demoler de una vez.
  {
    key: "dismantle_structure",
    version: 1,
    labelKey: "action.dismantle_structure.label",
    descriptionKey: "action.dismantle_structure.description",
    targetKinds: ["building"],
    requiredKnowledge: [{ facet: "structure", minimumState: "inspected" }],
    revealsKnowledge: [],
    priority: "dismantling_recycling",
    characteristicIds: ["strength", "technique"],
    skillIds: ["construction"],
    profile: "balanced_50_50",
    classification: "guided",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_building_standing" }, { kind: "requires_known_structure" }, { kind: "requires_irreversible_confirmation" }],
    difficulty: 4,
    model: "d",
    baseWorkUnits: 240,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 3,
    maxParticipants: 4,
    rolesAllowed: [...ACCESS_ROLES, "logistics_support"],
    phases: [...PREPARED_PHASES],
    paceApplies: true,
    attentionApplies: true,
    irreversible: true,
  },
  {
    key: "demolish_building",
    version: 1,
    labelKey: "action.demolish_building.label",
    descriptionKey: "action.demolish_building.description",
    targetKinds: ["building"],
    requiredKnowledge: [{ facet: "structure", minimumState: "inspected" }],
    revealsKnowledge: [],
    priority: "dismantling_recycling",
    characteristicIds: ["strength"],
    skillIds: ["construction"],
    profile: "physical_70_30",
    classification: "open",
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_building_standing" }, { kind: "requires_known_structure" }, { kind: "requires_irreversible_confirmation" }],
    difficulty: 2,
    model: "d",
    baseWorkUnits: 80,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 3,
    maxParticipants: 4,
    rolesAllowed: [...ACCESS_ROLES, "logistics_support"],
    phases: [...PREPARED_PHASES],
    paceApplies: true,
    attentionApplies: false,
    irreversible: true,
  },
];

/** Claves de los métodos S9 (acceso, instalaciones, acabados y estructura). */
export const EXPLOITATION_ACTION_KEYS: ReadonlySet<string> = new Set(EXPLOITATION_ACTION_METHODS.map((m) => m.key));

/** Métodos S9 que mutan un acceso y, por tanto, la navegación y la logística en el mismo límite causal. */
export const ACCESS_MUTATING_ACTION_KEYS: ReadonlySet<string> = new Set([
  "open_closure",
  "close_closure",
  "lock_closure",
  "unlock_closure",
  "force_closure",
  "clear_obstruction",
  "barricade_opening",
  "board_up_opening",
  "reinforce_closure",
  "repair_closure",
  "remove_closure",
  "destroy_closure",
  "install",
]);

/** Litros que produce una extracción completa de `draw_water` (S7, provisional y documentado en `docs/STATUS.md`). */
export const DRAW_WATER_LITERS_PER_JOB = 10;

/**
 * Métodos S10 (entorno mutable inicial y ciclo agrícola, `DEC-0020`, WLD-010
 * §3.5-§3.7, SET-011 §3.2). Mismo motor D determinista que el resto del
 * catálogo (`packages/simulation-core/src/v2/terrain/` y
 * `.../v2/agriculture/`); `s10WorkUnits` fija la duración real según la
 * superficie o longitud del blanco concreto, igual que S9 hace con la
 * huella o la receta de una instalación.
 */
function terrainMethod(input: Pick<ActionMethodDefinition, "key" | "priority" | "targetKinds" | "characteristicIds" | "skillIds" | "profile" | "difficulty" | "hardRequirements"> & Partial<ActionMethodDefinition>): ActionMethodDefinition {
  return {
    version: 1,
    labelKey: `action.${input.key}.label`,
    descriptionKey: `action.${input.key}.description`,
    requiredKnowledge: [],
    revealsKnowledge: [],
    classification: "open",
    model: "d",
    baseWorkUnits: 30,
    unit: "minutes",
    minParticipants: 1,
    recommendedParticipants: 1,
    maxParticipants: 3,
    rolesAllowed: ["responsible", "primary_executor", "operational_helper"],
    phases: ["validate", "travel", "prepare", "execute", "record_result"],
    paceApplies: true,
    attentionApplies: false,
    irreversible: false,
    ...input,
  };
}

export const TERRAIN_ACTION_METHODS: readonly ActionMethodDefinition[] = [
  terrainMethod({
    key: "clear_vegetation",
    priority: "logging",
    targetKinds: ["terrain_area", "cultivation_plot"],
    characteristicIds: ["strength"],
    skillIds: [],
    profile: "physical_70_30",
    difficulty: 1,
    hardRequirements: [{ kind: "known_target" }],
  }),
  terrainMethod({
    key: "clear_debris",
    priority: "logistics",
    targetKinds: ["terrain_area", "cultivation_plot"],
    characteristicIds: ["strength"],
    skillIds: [],
    profile: "physical_70_30",
    difficulty: 1,
    hardRequirements: [{ kind: "known_target" }],
  }),
  terrainMethod({
    key: "prepare_soil",
    priority: "agriculture_priority",
    targetKinds: ["cultivation_plot"],
    characteristicIds: ["strength", "endurance"],
    skillIds: ["agriculture"],
    profile: "physical_70_30",
    difficulty: 2,
    hardRequirements: [{ kind: "known_target" }],
  }),
  terrainMethod({
    key: "sow",
    priority: "agriculture_priority",
    targetKinds: ["cultivation_plot"],
    characteristicIds: ["dexterity"],
    skillIds: ["agriculture"],
    profile: "physical_70_30",
    difficulty: 2,
    hardRequirements: [{ kind: "known_target" }],
    phases: ["validate", "travel", "prepare", "execute", "record_result"],
  }),
  terrainMethod({
    key: "tend_crop",
    priority: "agriculture_priority",
    targetKinds: ["cultivation_plot"],
    characteristicIds: ["endurance"],
    skillIds: ["agriculture"],
    profile: "physical_70_30",
    difficulty: 1,
    hardRequirements: [{ kind: "known_target" }],
    baseWorkUnits: 20,
  }),
  terrainMethod({
    key: "harvest",
    priority: "agriculture_priority",
    targetKinds: ["cultivation_plot"],
    characteristicIds: ["dexterity", "endurance"],
    skillIds: ["agriculture"],
    profile: "physical_70_30",
    difficulty: 1,
    hardRequirements: [{ kind: "known_target" }],
  }),
  terrainMethod({
    key: "clear_road",
    priority: "logistics",
    targetKinds: ["linear_feature"],
    characteristicIds: ["strength"],
    skillIds: [],
    profile: "physical_70_30",
    difficulty: 1,
    hardRequirements: [{ kind: "known_target" }],
    phases: ["validate", "travel", "execute", "record_result"],
  }),
  terrainMethod({
    key: "remove_way_function",
    priority: "construction_fortification",
    targetKinds: ["linear_feature"],
    characteristicIds: ["strength"],
    skillIds: ["construction"],
    profile: "physical_70_30",
    difficulty: 2,
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_irreversible_confirmation" }],
    irreversible: true,
    phases: ["validate", "travel", "execute", "record_result"],
  }),
  terrainMethod({
    key: "build_barrier",
    priority: "construction_fortification",
    targetKinds: ["barrier_segment"],
    characteristicIds: ["strength", "dexterity"],
    skillIds: ["carpentry", "construction"],
    profile: "physical_70_30",
    classification: "improvisable",
    difficulty: 2,
    hardRequirements: [{ kind: "known_target" }, { kind: "requires_concrete_materials" }],
    recommendedParticipants: 2,
  }),
];

/** Claves de los métodos S10 (entorno mutable y agricultura). */
export const TERRAIN_ACTION_KEYS: ReadonlySet<string> = new Set(TERRAIN_ACTION_METHODS.map((m) => m.key));

/** Métodos S10 cuyo blanco se reserva en exclusiva: dos trabajos nunca despejan, preparan, siembran o cosechan la misma superficie/tramo a la vez. */
export const TERRAIN_EXCLUSIVE_ACTION_KEYS: ReadonlySet<string> = new Set(TERRAIN_ACTION_METHODS.map((m) => m.key));

/** Métodos S7 cuyo blanco (y, en almacenamiento, el elemento movido) se reserva en exclusiva (S7 §7.7/§9: "reservas impiden doble uso"). */
export const EXCLUSIVE_TARGET_ACTION_KEYS: ReadonlySet<string> = new Set([
  "collect",
  "store",
  "retrieve_from_storage",
  "repair",
  "disassemble_selective",
  "disassemble_destructive",
  "test_installation",
  "draw_water",
  "transport",
  // S9: accesos, edificios, instalaciones, acabados y la bomba desinstalada/instalada se comprometen en exclusiva.
  ...EXPLOITATION_ACTION_METHODS.map((m) => m.key),
  // S10: superficie de fondo, tramo de vía, parcela de cultivo y tramo de barrera se comprometen en exclusiva.
  ...TERRAIN_ACTION_METHODS.map((m) => m.key),
]);

export const ACTION_METHODS_BY_KEY: ReadonlyMap<string, ActionMethodDefinition> = new Map(
  [...ACTION_METHODS, ...OBJECT_ACTION_METHODS, ...EXPLOITATION_ACTION_METHODS, ...TERRAIN_ACTION_METHODS].map((m) => [m.key, m]),
);
