/**
 * Diccionario de textos de interfaz para las claves (`*Key`) que produce
 * el núcleo de simulación (biografía, relaciones, pertenencias, registro
 * operacional, motivos de bloqueo). Vive en `catalogs` porque es un dato
 * versionado de presentación, no una regla de simulación ni prosa libre
 * incrustada en componentes.
 */
export const COPY_KEYS: Readonly<Record<string, string>> = {
  // Origen y aficiones.
  "biography.origin.regional_town": "Creció en una localidad de la región, antes del colapso.",
  "hobbies.gardening": "Le gusta cuidar plantas y pequeños huertos.",
  "hobbies.tinkering": "Disfruta desmontar y reparar aparatos por curiosidad.",
  "hobbies.hiking": "Pasa su tiempo libre haciendo rutas de montaña.",
  "hobbies.cooking": "Cocina para familia y amigos siempre que puede.",
  "hobbies.reading": "Es una lectora empedernida.",
  "hobbies.birdwatching": "Observa aves y fauna silvestre en su tiempo libre.",

  // Profesiones (identidad + experiencia resumida).
  "profession.field_nurse": "Enfermera de atención primaria.",
  "profession.field_nurse.experience": "Años atendiendo urgencias menores y primeros auxilios en un centro de salud rural.",
  "profession.maintenance_electrician": "Electricista de mantenimiento.",
  "profession.maintenance_electrician.experience": "Reparaciones eléctricas y mecánicas en edificios e instalaciones industriales.",
  "profession.mountain_guide": "Guía de montaña.",
  "profession.mountain_guide.experience": "Rutas de senderismo y orientación en terreno difícil durante años.",
  "profession.delivery_driver": "Conductora de reparto.",
  "profession.delivery_driver.experience": "Transporte y logística de mercancías por carretera, con nociones de cocina casera.",
  "profession.primary_school_teacher": "Maestra de primaria.",
  "profession.primary_school_teacher.experience": "Años enseñando y mediando en conflictos entre niños y familias.",
  "profession.park_ranger": "Guarda forestal.",
  "profession.park_ranger.experience": "Vigilancia y seguimiento de fauna en un parque natural.",

  // Fortalezas y limitaciones por arquetipo.
  "field_nurse.strengths": "Mantiene la calma ante heridas y sabe priorizar quién necesita ayuda primero.",
  "field_nurse.limitations": "Tiene poca experiencia con maquinaria o trabajos de fuerza.",
  "maintenance_electrician.strengths": "Resuelve problemas técnicos con lo que tenga a mano.",
  "maintenance_electrician.limitations": "Le cuesta relacionarse con desconocidos.",
  "mountain_guide.strengths": "No se pierde y aguanta bien el esfuerzo físico prolongado.",
  "mountain_guide.limitations": "Tiene poca formación técnica o sanitaria.",
  "delivery_driver.strengths": "Organizada y resolutiva bajo presión de tiempo.",
  "delivery_driver.limitations": "Poca experiencia en trabajos manuales especializados.",
  "primary_school_teacher.strengths": "Sabe explicar y calmar a un grupo asustado.",
  "primary_school_teacher.limitations": "Se agota físicamente con rapidez.",
  "park_ranger.strengths": "Detecta movimiento y peligro antes que los demás.",
  "park_ranger.limitations": "No tiene experiencia sanitaria ni social.",

  // Interpretación del acontecimiento compartido (la marcha de cuatro días).
  "shared_event.interpretation.field_nurse": "«Lo que importa es que nadie se quedó atrás sin ayuda.»",
  "shared_event.interpretation.maintenance_electrician": "«Sobrevivimos porque improvisamos soluciones sobre la marcha.»",
  "shared_event.interpretation.mountain_guide": "«Conocer el terreno nos salvó más de una vez.»",
  "shared_event.interpretation.delivery_driver": "«Mantener la cabeza fría y repartir tareas nos sacó adelante.»",
  "shared_event.interpretation.primary_school_teacher": "«Lo más duro fue mantener la calma del grupo.»",
  "shared_event.interpretation.park_ranger": "«Vi el peligro antes de que llegara, y eso marcó la diferencia.»",

  // Pertenencias de llegada.
  "possession.kitchen_knife": "Cuchillo de cocina",
  "possession.hiking_axe": "Piqueta de montaña",
  "possession.iron_pipe": "Barra de hierro",
  "possession.wood_axe": "Hacha de leñador",
  "possession.personal_pack": "Mochila personal",

  // Condiciones de llegada.
  "arrival.fatigue.significant": "Cansancio acumulado tras cuatro días de marcha.",
  "arrival.rest_deficit.two_short_nights": "Solo ha dormido de forma completa dos de las últimas cuatro noches.",
  "arrival.hardship.scarce_water": "El agua ha escaseado durante buena parte del camino.",

  // Relaciones.
  "relationship.strong_prior_bond": "Vínculo fuerte y positivo de antes del colapso.",
  "relationship.prior_acquaintance": "Se conocían de antes, aunque no eran íntimos.",
  "relationship.forged_during_the_march": "El vínculo nació durante los cuatro días de marcha.",
  "relationship.strained_by_recent_decision": "La relación se ha resentido por una decisión reciente.",
  "relationship.newcomer_vouched_for": "Se incorporó al grupo hace pocos días; todavía genera cautela.",

  // Motivos de rechazo/bloqueo de una orden de movimiento.
  "move_rejection.destination_outside_world": "El destino está fuera de los límites conocidos del mundo.",
  "move_rejection.destination_hidden": "Ese punto todavía no se ha observado ni se conoce su ruta.",
  "move_rejection.destination_not_transitable": "No es posible caminar hasta ese punto.",
  "move_rejection.no_known_route": "No existe una ruta conocida hasta ese destino.",
  "move_rejection.person_already_ordered": "Esta persona ya tiene una orden de movimiento en curso.",
  "move_rejection.stale_or_duplicate_command": "La orden ha llegado duplicada o ya no es válida.",

  // Registro operacional.
  "log.game_created": "Partida creada.",
  "log.speed_or_pause_changed": "Se cambió la velocidad o la pausa.",
  "log.move_order_accepted": "Orden de movimiento aceptada.",
  "log.move_order_rejected": "Orden de movimiento rechazada.",
  "log.movement_started": "Movimiento iniciado.",
  "log.movement_completed": "Movimiento completado.",
  "log.movement_blocked": "Movimiento bloqueado.",
  "log.movement_cancelled": "Movimiento cancelado.",
  "log.priority_changed": "Prioridad actualizada.",
  "log.room_entered": "Entró en una estancia.",
  "log.room_exited": "Salió de una estancia.",
  "log.discovery_upgraded": "Se descubrió algo nuevo.",

  // Puntos de interés del mapa.
  "landmark.distant_silo": "Silo distante",
  "landmark.old_signpost": "Poste de señalización antiguo",
  "structure.shelter_candidate": "Posible refugio",

  // Acciones activas del motor de resolución (S4-S6, WEB-002 §5.2/§10).
  "action.recognize.label": "Reconocer",
  "action.observe.label": "Observar",
  "action.inspect.label": "Inspeccionar",
  "action.register.label": "Registrar",
  "action.drink.label": "Beber",
  "action.eat.label": "Comer",
  "action.rest.label": "Descansar",
  "target.unidentified_place": "Lugar sin identificar",
  "target.room": "Estancia conocida",
  "room_role.entry_distributor": "Entrada",
  "room_role.common_space": "Sala de estar",
  "room_role.kitchen": "Cocina",
  "room_role.bathroom": "Baño",
  "room_role.bedroom": "Dormitorio",
  "room_role.domestic_storage": "Trastero",
  "room_role.main_multiuse_room": "Estancia principal",
  "room_role.kitchen_solution": "Rincón de cocina",
  "room_role.rest_area": "Zona de descanso",
  "room_role.minimal_storage": "Almacén pequeño",
  "room_role.public_sales_floor": "Sala de ventas",
  "room_role.checkout": "Caja",
  "room_role.shelving_display": "Estanterías de venta",
  "room_role.back_storage": "Almacén trasero",
  "room_role.restroom": "Aseo",
  "room_role.customer_access": "Acceso de clientes",
  "room_role.service_or_loading_access": "Acceso de carga",
  "room_role.work_area": "Zona de trabajo",
  "room_role.workbench_tools": "Banco y herramientas",
  "room_role.parts_storage": "Almacén de piezas",
  "room_role.minimal_office": "Oficina",
  "room_role.restroom_locker": "Vestuario",
  "room_role.personnel_access": "Acceso de personal",
  "room_role.wide_gate": "Portón",
  "target.room_rest": "Descansar aquí (soporte disponible en la estancia)",
  "resource.water": "Agua",
  "resource.fresh_food": "Alimento fresco",
  "resource.preserved_food": "Alimento conservado",
  "resource.seeds": "Semillas",
  "resource.healing_material": "Material de cura",
  "resource.wood_and_planks": "Madera y tablones",
  "resource.sheet_metal": "Chapa metálica",
  "resource.wiring": "Cableado",
  "resource.electrical_components_i": "Componentes eléctricos I",
  "resource.mechanical_parts_i": "Piezas mecánicas I",
  "resource.electric_motors_ii": "Motores eléctricos II",

  // Objetos y recursos profundos de S7 (WEB-002 §15).
  "action.collect.label": "Recoger",
  "action.store.label": "Almacenar",
  "action.retrieve_from_storage.label": "Retirar de almacenamiento",
  "action.repair.label": "Reparar",
  "action.disassemble_selective.label": "Desmontar (selectivo)",
  "action.disassemble_destructive.label": "Desguazar (destructivo)",
  "object.personal_liquid_container.bottle": "Botella",
  "object.personal_liquid_container.canteen": "Cantimplora",
  "object.work_container.bucket": "Cubo",
  "object.work_container.jerry_can": "Garrafa",
  "object.transport_container.backpack": "Mochila",
  "object.transport_container.sack": "Saco",
  "object.transport_container.box": "Caja",
  "object.storage_furniture.wardrobe": "Armario",
  "object.storage_furniture.shelf": "Estantería",
  "object.storage_furniture.storage_box": "Caja de almacén",
  "object.technical_appliance.fridge": "Frigorífico",
  "object.light_source.lantern": "Farol",
  "object.light_source.oil_lantern": "Farol de aceite",
  "object.rest_furniture.bedroll": "Rollo de dormir",
  "object.human_transport.wheelbarrow": "Carretilla",
  "object.human_transport.handcart": "Carro de mano",
  "object.personal_liquid_container.generic": "Recipiente de líquido",
  "object.tool_set.generic": "Herramientas",
  "object.storage_furniture.generic": "Caja de almacenamiento",
  "object.tool_set.hand_hoe": "Azada de mano",
  "object.work_container.drum": "Bidón",
  "object.work_container.cooking_pot": "Olla",
  "object.light_source.flashlight": "Linterna",
  "object.light_source.lighter": "Mechero",
  "object.improvised_tool_or_weapon.kitchen_knife": "Cuchillo de cocina",
  "object.improvised_tool_or_weapon.pocket_knife": "Navaja",
  "object.improvised_tool_or_weapon.hammer": "Martillo",
  "object.improvised_tool_or_weapon.crowbar": "Palanca",
  "object.improvised_tool_or_weapon.hand_axe": "Hacha de mano",
  "object.improvised_tool_or_weapon.saw": "Sierra",
  "object.improvised_tool_or_weapon.shovel": "Pala",
  "object.improvised_tool_or_weapon.hoe": "Azada",
  "object.improvised_tool_or_weapon.hiking_axe": "Piolet",
  "object.improvised_tool_or_weapon.iron_pipe": "Tubo de hierro",
  "object.improvised_tool_or_weapon.wood_axe": "Hacha de leña",
  "object.tool_set.basic": "Herramientas básicas",
  "object.tool_set.carpentry": "Herramientas de carpintería",
  "object.tool_set.mechanics": "Herramientas de mecánica",
  "object.tool_set.agriculture": "Herramientas de agricultura",
  "object.rest_furniture.mattress": "Colchón",
  "object.rest_furniture.simple_bed": "Cama sencilla",
  "object.workbench.workbench": "Banco de trabajo",
  "object.technical_installation.hand_pump": "Bomba de agua manual",
  "object.installed_closure_object.door": "Puerta",
  "object.installed_closure_object.gate": "Portón",
  "family.personal_liquid_container": "Recipiente personal de líquido",
  "family.work_container": "Recipiente de trabajo",
  "family.transport_container": "Contenedor de transporte",
  "family.storage_furniture": "Almacenamiento/mobiliario",
  "family.localized_consumable": "Consumible localizado",
  "family.light_source": "Luz portátil",
  "family.improvised_tool_or_weapon": "Herramienta o arma improvisada",
  "family.tool_set": "Conjunto de herramientas",
  "family.rest_furniture": "Soporte de descanso",
  "family.workbench": "Puesto de trabajo",
  "family.technical_appliance": "Aparato técnico completo",
  "family.technical_installation": "Instalación técnica",
  "family.installed_closure_object": "Cierre instalado",
  "family.human_transport": "Transporte humano",
  "action.test_installation.label": "Probar instalación",
  "action.draw_water.label": "Extraer agua con la bomba",
  "container.label": "Contenedor",
  "location.carried": "Lo lleva",
  "location.room": "En una estancia conocida",
  "location.container": "Dentro de",
  "location.exterior": "En el exterior",
  "location.load": "En una carga",
  "location.transfer_point": "En",
  "load.label": "carga en tránsito",

  // Transporte y logística local (S8 — Puerta B).
  "action.transport.label": "Transportar",
  "action.transport.description": "Llevar una carga real hasta un destino con un método de transporte concreto o Auto.",
  "transport_method.auto": "Auto (el mejor método conocido)",
  "transport_method.hand_carry": "A pulso",
  "transport_method.personal_container": "En recipiente personal (mochila, saco…)",
  "transport_method.coordinated_carry": "Porte coordinado (2 o más personas)",
  "transport_method.wheelbarrow": "Carretilla",
  "transport_method.handcart": "Carro de mano",
  "transport_step.plan": "Planificando",
  "transport_step.reserve": "Reservando carga, medio y personas",
  "transport_step.retrieve_means": "Recuperando el medio",
  "transport_step.go_to_origin": "Yendo a la carga",
  "transport_step.load": "Cargando",
  "transport_step.traverse": "Recorriendo la ruta",
  "transport_step.unload": "Descargando",
  "transport_step.deposit": "Almacenando/entregando",
  "transport_step.park": "Estacionando el medio",
  "transport_step.done": "Terminado",
  "transport_plan.auto.hand_carry": "Auto eligió llevarlo a pulso.",
  "transport_plan.auto.personal_container": "Auto eligió el recipiente personal.",
  "transport_plan.auto.coordinated_carry": "Auto eligió el porte coordinado.",
  "transport_plan.auto.wheelbarrow": "Auto eligió la carretilla.",
  "transport_plan.auto.handcart": "Auto eligió el carro de mano.",
  "transport_plan.imposed": "Método impuesto por la orden.",
  "transport_plan.imposed_staged": "Método impuesto: el medio no cabe hasta el destino y se descargará en un acceso.",
  "transfer_point.gate": "Punto de transferencia en el portón",
  "transfer_point.loading_access": "Punto de transferencia en el acceso de carga",
  "transfer_point.building_access": "Punto de transferencia en el acceso",
  "destination.arrival_point": "Punto de llegada del grupo (exterior)",
  "destination.exterior_point": "Punto exterior",
  "noise.quiet": "Silencioso",
  "noise.audible": "Audible",
  "noise.loud": "Ruidoso",
  "load_placement.carried": "La llevan",
  "load_placement.on_means": "Montada en el medio",
  "load_placement.deposited": "Depositada",
  "meansDisposition.park_at_destination": "Estacionar en destino",
  "meansDisposition.return_to_origin": "Devolver a su sitio",
  "block.no_transport_destination": "Falta elegir un destino para el traslado.",
  "block.transport_not_viable": "Ningún método conocido puede hacer este traslado.",
  "block.load_too_heavy_for_method": "Demasiado pesado para este método (el bulto sí cabría).",
  "block.load_too_bulky_for_method": "Demasiado voluminoso para este método (el peso sí se podría).",
  "block.load_exceeds_team_capacity": "El equipo no puede llevar toda la carga en un solo viaje.",
  "block.handling_incompatible_with_method": "La carga no puede viajar así (líquido, frágil, larga o debe ir vertical).",
  "block.cargo_requires_coordinated_carry": "Hace falta porte coordinado: una sola persona no puede con esto.",
  "block.method_requires_more_carriers": "Este método necesita más personas en el equipo.",
  "block.waiting_for_carriers": "Esperando a que el resto del equipo quede libre.",
  "block.carriers_unavailable": "Alguien del equipo está comprometido en otro trabajo.",
  "block.route_incompatible_with_method": "La ruta conocida no admite este método o esta carga (anchura de accesos o terreno).",
  "block.route_crosses_forbidden_zone": "La única ruta conocida atraviesa una zona prohibida.",
  "block.route_obstructed": "Un acceso de la ruta quedó bloqueado durante el traslado.",
  "block.target_in_forbidden_zone": "El objetivo está dentro de una zona prohibida.",
  "block.no_known_means": "No se conoce ningún medio de ese tipo.",
  "block.means_not_functional": "El medio está averiado o incompleto: hay que repararlo.",
  "block.means_reserved": "Otro trabajo ya está usando ese medio.",
  "block.means_in_use": "Otra persona está usando ese medio.",
  "block.means_loaded": "El medio lleva otra carga: hay que descargarla antes.",
  "block.means_unknown": "La comunidad no sabe dónde está ese medio.",
  "block.means_no_longer_exists": "El medio ya no existe.",
  "block.no_personal_container": "No lleva un recipiente personal donde quepa la carga.",
  "block.cargo_not_together": "La carga está repartida en lugares distintos.",
  "block.cargo_held_by_other_person": "Parte de la carga la lleva alguien fuera del equipo.",
  "block.cargo_fixed_installation": "Está instalado o fijo: no se puede transportar.",
  "block.destination_unknown": "Ese destino no se conoce todavía.",
  "block.destination_carried_container": "Ese contenedor lo lleva una persona: no es un destino fijo.",
  "block.no_cargo_selected": "No hay carga seleccionada.",
  "block.no_transport_plan": "El traslado no tiene plan.",
  "block.cancelled_by_order": "Cancelado por orden.",
  "log.transport_planned": "Se planificó un traslado.",
  "log.transport_means_retrieved": "Se recuperó un medio de transporte.",
  "log.load_prepared": "Se preparó una carga.",
  "log.access_traversed": "Una carga atravesó un acceso.",
  "log.transport_route_blocked": "Un traslado encontró la ruta bloqueada.",
  "log.transport_noise_emitted": "Un traslado hizo ruido por el camino.",
  "log.load_delivered": "Se entregó una carga en su destino.",
  "log.load_transferred": "Se descargó una carga en un punto de transferencia.",
  "log.load_deposited": "Una carga quedó depositada donde estaba.",
  "log.transport_means_parked": "Se dejó un medio de transporte.",
  "freshness.fresh": "Fresco",
  "freshness.deteriorating": "Empezando a deteriorarse",
  "freshness.spoiled": "Echado a perder",
  "functional_state.functional": "Funcional",
  "functional_state.degraded": "Degradado",
  "functional_state.broken": "Averiado",
  "functional_state.incomplete": "Incompleto",
  "functional_state.repairable": "Reparable",
  "functional_state.irreparable": "Irreparable",
  "functional_state.parts_only": "Solo piezas",
  "functional_state.untested": "Sin probar",
  "block.container_full": "El contenedor no tiene capacidad libre suficiente.",
  "block.container_incompatible": "El contenedor no admite este tipo de objeto.",
  "block.container_not_empty": "Hay que vaciar el contenedor antes de desmontarlo.",
  "block.container_unusable": "El contenedor ya no puede usarse para guardar nada.",
  "block.no_storage_container_selected": "No se ha elegido un contenedor real.",
  "block.no_storage_item_selected": "No se ha elegido qué guardar o retirar.",
  "block.item_not_in_container": "Ese objeto ya no está en este contenedor.",
  "block.item_not_at_storage_site": "El objeto no está aquí: usa «Transportar» para llevarlo hasta el contenedor.",
  "block.target_reserved": "Otro trabajo ya está usando ese objeto o contenedor.",
  "block.installation_not_functional": "La instalación no funciona: hay que diagnosticarla y repararla.",
  "block.installation_disconnected": "La instalación no está conectada a una fuente real.",
  "block.food_spoiled": "El alimento está echado a perder: no es consumible.",
  "block.transport_loaded": "Hay que descargar el medio antes de desmontarlo.",
  "block.item_already_stored": "Ya está guardado en ese contenedor.",
  "block.requires_diagnosis": "Hay que probar/diagnosticar la instalación antes de repararla.",
  "block.no_liquid_vessel": "No hay ningún recipiente con hueco a mano para recoger el agua.",
  "log.object_broke_down": "Un objeto se averió por desgaste.",
  "log.installation_tested": "Se probó una instalación.",
  "log.water_drawn": "Se extrajo agua con la bomba.",
  "log.resource_lot_deteriorated": "Un alimento cambió de estado de conservación.",

  // Motivos de bloqueo de trabajos (S4-S6, WEB-002 §5.9/§11.2).
  "block.target_no_longer_exists": "El objetivo ya no existe.",
  "block.no_resource_lot_selected": "No se ha seleccionado ningún recurso.",
  "block.resource_exhausted": "El recurso se ha agotado.",
  "block.resource_reserved": "Ya está reservado por otro trabajo.",
  "block.object_reserved": "Ya está reservado por otro trabajo.",
  "block.requirement_failed": "No se cumple un requisito necesario.",
  "block.target_unreachable": "No hay ruta conocida hasta el objetivo.",
  "block.no_known_route": "No hay ruta conocida hasta el objetivo.",
  "block.severe_outcome": "El intento salió mal y hay que volver a intentarlo con un cambio real.",
  "block.critical_need_autoprotection": "Interrumpido: una necesidad crítica exige atención inmediata.",
  "block.no_known_solution_for_hydration": "No se conoce ninguna fuente de agua accesible.",
  "block.no_known_solution_for_nutrition": "No se conoce ningún alimento accesible.",
  "block.no_known_solution_for_rest": "No se conoce ningún lugar de descanso accesible.",
  "block.no_transformation_profile": "Este objeto no tiene una receta de reparación/desmontaje conocida.",
  "block.missing_materials": "Faltan los materiales concretos necesarios aquí mismo.",
  "block.irreversible_not_confirmed": "Falta confirmar el coste irreversible de esta acción.",
  "block.requires_transport_method": "Es demasiado grande para recogerlo sin más: usa «Transportar» con un método adecuado.",

  // Registro operacional — trabajos y necesidades.
  "log.job_created": "Se creó un trabajo.",
  "log.job_state_changed": "Un trabajo cambió de estado.",
  "log.job_phase_changed": "Un trabajo avanzó de fase.",
  "log.job_assignment_changed": "Cambió la asignación de un trabajo.",
  "log.reservation_created": "Se reservó un recurso para un trabajo.",
  "log.reservation_released": "Se liberó una reserva.",
  "log.work_episode_created": "Se resolvió un intento incierto.",
  "log.need_changed": "Una necesidad cambió de estado.",
  "log.consumption_happened": "Se consumió un recurso.",
  "log.rest_progressed": "Progresó un descanso.",
  "log.systemic_intention_created": "Se generó una intención por necesidad crítica.",
  "log.work_interrupted": "Un trabajo se interrumpió.",
  "log.zone_changed": "Cambió una zona.",
  "log.designation_changed": "Cambió una designación.",
  "log.object_collected": "Se recogió un objeto.",
  "log.object_stored": "Se almacenó un objeto.",
  "log.object_retrieved": "Se retiró un objeto del almacenamiento.",
  "log.object_repaired": "Se intentó una reparación.",
  "log.object_disassembled": "Se desmontó un objeto.",
  "log.resource_lot_consumed": "Se consumió un lote de recurso.",
  "log.resource_lot_split": "Se dividió un lote de recurso.",
  "log.resource_lot_merged": "Se fusionaron dos lotes de recurso.",

  // Perfiles de lugar (CAT-004) usados como etiqueta de blanco contextual.
  "place.RES-10": "Casa familiar mediana",
  "place.RES-17": "Cabaña",
  "place.COM-02": "Supermercado pequeño",
  "place.TAL-01": "Taller mecánico",
  "place.ENV-01": "Fuente local de agua",
  "place.ENV-02": "Campo o parcela abierta",
  "place.ENV-03": "Bosque o matorral",
  "place.ENV-04": "Carretera o camino",

  "action.recognize.description": "Identifica a distancia qué tipo de lugar es.",
  "action.observe.description": "Observa un lugar, acceso o estancia con calma y revela sus accesos.",
  "action.inspect.description": "Examina de cerca estructura y accesos (en un edificio: época, materiales y etapas de su estructura).",
  "action.register.description": "Registra una estancia: revela su contenido y mobiliario reales (primera vida: saqueo).",
  "action.drink.description": "Bebe de un lote de agua conocido y al alcance.",
  "action.eat.description": "Come de un lote de alimento conocido y en buen estado.",
  "action.rest.description": "Descansa; rinde más en cama o en una estancia habitable que en el suelo.",
  "action.collect.description": "Recoge entero un objeto o lote suelto (nunca desmonta ni instala).",
  "action.store.description": "Guarda un objeto o lote en un contenedor real con capacidad.",
  "action.retrieve_from_storage.description": "Saca de un contenedor un objeto o una parte de un lote.",
  "action.repair.description": "Repara con materiales concretos; nunca eleva la calidad original.",
  "action.disassemble_selective.description": "Desmonta un objeto o mueble conservando más componentes; elimina su función. Irreversible.",
  "action.disassemble_destructive.description": "Desguaza un objeto o mueble: más rápido, conserva menos. Irreversible.",
  "action.test_installation.description": "Prueba una instalación técnica y revela su estado real.",
  "action.draw_water.description": "Extrae agua con una bomba funcional conectada a su fuente, hacia recipientes reales.",

  "furniture.coat_rack": "Perchero",
  "furniture.shoe_bench": "Banco zapatero",
  "furniture.sofa": "Sofá",
  "furniture.low_table": "Mesa baja",
  "furniture.kitchen_counter": "Mueble bajo de cocina",
  "furniture.stove": "Cocina de fuegos",
  "furniture.fridge": "Frigorífico",
  "furniture.sink": "Lavabo/fregadero",
  "furniture.tub": "Bañera",
  "furniture.bed": "Cama",
  "furniture.wardrobe": "Armario",
  "furniture.storage_shelf": "Estantería",
  "furniture.trunk": "Baúl",
  "furniture.small_table": "Mesa pequeña",
  "furniture.camp_stove_counter": "Hornillo de camping",
  "furniture.cot": "Catre",
  "furniture.display_table": "Mesa expositora",
  "furniture.counter_till": "Mostrador con caja",
  "furniture.shelving_unit": "Estantería de tienda",
  "furniture.pallet_rack": "Estantería de palés",
  "furniture.entry_mat": "Felpudo",
  "furniture.loading_bench": "Banco de carga",
  "furniture.hydraulic_lift": "Elevador hidráulico",
  "furniture.workbench": "Banco de trabajo",
  "furniture.parts_shelf": "Estantería de piezas",
  "furniture.desk": "Escritorio",
  "furniture.locker": "Taquilla",
  "furniture.gate_rail": "Guía del portón",

  // --- S9 — Puerta C: accesos, explotación progresiva de edificios y habitabilidad ---
  "move_rejection.access_no_longer_passable": "Un acceso de la ruta ha dejado de ser transitable; la persona se ha detenido donde estaba.",
  "action.open_closure.label": "Abrir cierre",
  "action.open_closure.description": "Abre una puerta, portón o ventana cerrada (no bloqueada).",
  "action.close_closure.label": "Cerrar cierre",
  "action.close_closure.description": "Cierra una puerta, portón o ventana abierta.",
  "action.lock_closure.label": "Bloquear acceso",
  "action.lock_closure.description": "Echa el cierre de una puerta o portón: impide el paso hasta desbloquearlo.",
  "action.unlock_closure.label": "Desbloquear acceso",
  "action.unlock_closure.description": "Quita el bloqueo de un cierre: desde cualquier lado si lo echó la comunidad; si se encontró bloqueado, solo desde dentro.",
  "action.force_closure.label": "Forzar cierre",
  "action.force_closure.description": "Fuerza un cierre bloqueado: lo abre pero rompe el mecanismo, lo daña y hace ruido.",
  "action.clear_obstruction.label": "Despejar obstrucción",
  "action.clear_obstruction.description": "Retira una barricada, un tapiado, escombros o un mueble que bloquea el paso; recupera parte del material.",
  "action.barricade_opening.label": "Reforzar con barricada",
  "action.barricade_opening.description": "Bloquea un acceso con tablones concretos (6 kg de madera): impide el paso hasta despejarla.",
  "action.board_up_opening.label": "Tapiar acceso",
  "action.board_up_opening.description": "Cierra funcionalmente la abertura con material concreto (12 kg de madera); la abertura sigue existiendo, pero ya no se atraviesa.",
  "action.reinforce_closure.label": "Reforzar cierre",
  "action.reinforce_closure.description": "Refuerza la puerta o el portón con tablones (4 kg de madera): forzarlo cuesta más.",
  "action.repair_closure.label": "Reparar cierre",
  "action.repair_closure.description": "Repara hojas, marco o mecanismo con materiales concretos (madera y, si el mecanismo está roto, una pieza mecánica).",
  "action.remove_closure.label": "Retirar puerta (preservándola)",
  "action.remove_closure.description": "Desmonta el cierre entero: queda como objeto localizado reutilizable y la abertura sigue abierta y transitable.",
  "action.destroy_closure.label": "Destruir cierre",
  "action.destroy_closure.description": "Rompe el cierre de forma destructiva: deja paso y madera de desecho, pero ninguna puerta reutilizable. Irreversible.",
  "action.install.label": "Instalar",
  "action.install.description": "Instala una puerta o portón recuperado en una abertura sin cierre compatible, o la bomba en una fuente de agua sin bomba.",
  "action.survey_installations.label": "Registro técnico de instalaciones",
  "action.survey_installations.description": "Una persona con conocimiento técnico identifica las instalaciones del edificio que otros no reconocen.",
  "action.disconnect_installation.label": "Desconectar instalación",
  "action.disconnect_installation.description": "Corta y deja segura una instalación antes de desmontarla; pierde su servicio.",
  "action.dismantle_installation.label": "Desmontar instalación",
  "action.dismantle_installation.description": "Desmontaje selectivo: recupera componentes enteros (cableado, diferenciales, tuberías...). Una extracción torpe pierde parte. Irreversible.",
  "action.uninstall_installation.label": "Desinstalar bomba entera",
  "action.uninstall_installation.description": "Desconecta la bomba y libera sus anclajes: queda entera y trasladable, pero la fuente deja de tener servicio hasta reinstalarla.",
  "action.strip_finish.label": "Retirar acabado",
  "action.strip_finish.description": "Retira con cuidado un acabado (ventana, sanitario, suelo...) conservando el material; reduce la habitabilidad para siempre.",
  "action.dismantle_structure.label": "Desmantelar estructura (por etapas)",
  "action.dismantle_structure.description": "Tercera vida: desmonta la estructura etapa a etapa recuperando materiales reutilizables. Lento, exige el edificio vacío. Irreversible.",
  "action.demolish_building.label": "Demoler edificio",
  "action.demolish_building.description": "Tercera vida destructiva: rápida, deja materiales masivos y escombros y destruye todo lo que quede dentro. El edificio deja de existir. Irreversible.",

  "block.building_demolished": "El edificio ha sido demolido: ya no existe como edificio.",
  "block.building_dismantled": "El edificio ha sido desmantelado: ya no existe como edificio.",
  "block.building_layers_unavailable": "Esta partida no tiene instalaciones, acabados ni estructura detallados para este edificio (partida anterior a S9).",
  "block.structure_not_inspected": "Hay que inspeccionar antes la estructura del edificio.",
  "block.installation_not_surveyed": "Nadie ha identificado todavía esa instalación con un registro técnico.",
  "block.no_installed_closure": "Ese acceso no tiene un cierre instalado.",
  "block.no_obstruction": "Ese acceso no tiene ninguna obstrucción que despejar.",
  "block.closure_already_open": "El cierre ya está abierto.",
  "block.closure_already_closed": "El cierre ya está cerrado.",
  "block.closure_locked": "El cierre está bloqueado: hay que desbloquearlo o forzarlo antes.",
  "block.closure_not_locked": "El cierre no está bloqueado.",
  "block.closure_already_locked": "El cierre ya está bloqueado.",
  "block.closure_cannot_lock": "Una ventana no se puede bloquear así.",
  "block.lock_broken": "El mecanismo está roto (se forzó): hay que repararlo antes de volver a bloquear.",
  "block.locked_from_other_side": "Está bloqueado desde dentro: solo se desbloquea desde el lado interior; si no, hay que forzarlo.",
  "block.opening_already_obstructed": "Ese acceso ya está obstruido.",
  "block.opening_obstructed": "Hay una obstrucción en ese acceso: hay que despejarla antes.",
  "block.closure_already_reinforced": "El cierre ya está reforzado.",
  "block.closure_cannot_reinforce": "Una ventana no se refuerza así.",
  "block.closure_not_damaged": "El cierre no necesita reparación.",
  "block.closure_cannot_remove": "Ese cierre no se retira entero en esta entrega.",
  "block.no_install_item_selected": "Falta elegir qué objeto se instala.",
  "block.install_incompatible": "Ese objeto no se puede instalar ahí.",
  "block.install_requires_single_object": "Para instalar hay que trasladar exactamente el objeto que se va a instalar.",
  "block.closure_does_not_fit_opening": "Ese cierre no encaja en la anchura de esa abertura (no se crean ni amplían huecos).",
  "block.opening_has_closure": "Esa abertura ya tiene un cierre instalado.",
  "block.place_not_water_source": "Ese lugar no es una fuente de agua donde instalar la bomba.",
  "block.place_already_equipped": "Esa fuente ya tiene una bomba instalada.",
  "block.item_not_at_install_site": "El objeto no está en el sitio: hay que traerlo antes (Transportar con destino «instalar»).",
  "block.installations_already_surveyed": "Las instalaciones de este edificio ya están registradas por completo.",
  "block.installation_not_connected": "La instalación ya no está conectada.",
  "block.installation_not_disconnected": "Hay que desconectar la instalación antes de desmontarla.",
  "block.installation_already_dismantled": "La instalación ya está desmontada.",
  "block.not_installed": "El objeto no está instalado.",
  "block.not_uninstallable": "Ese objeto no se desinstala entero.",
  "block.finish_already_recovered": "Ese acabado ya no está instalado.",
  "block.people_inside_building": "Hay personas dentro del edificio: deben salir antes.",
  "block.building_has_active_jobs": "Hay otros trabajos en curso sobre el edificio o su contenido.",
  "block.cargo_inside_building": "Hay cargas o puntos de transferencia dentro del edificio.",
  "block.building_not_emptied": "Hay que vaciar el edificio (contenido y mobiliario) antes de desmantelar su estructura.",
  "block.target_destroyed": "El objetivo desapareció con el edificio.",

  "log.access_changed": "Cambió un acceso (su navegación y logística se actualizan).",
  "log.installation_surveyed": "Se registraron instalaciones del edificio.",
  "log.installation_disconnected": "Se desconectó una instalación.",
  "log.installation_dismantled": "Se desmontó una instalación y se recuperaron componentes.",
  "log.finish_recovered": "Se retiró un acabado conservando su material.",
  "log.structure_dismantled": "Se desmanteló una etapa de la estructura.",
  "log.building_demolished": "Se demolió un edificio (irreversible).",
  "log.building_life_stage_changed": "Un edificio entró en una nueva vida de explotación.",
  "log.building_layer_exhausted": "Se agotó una capa de aprovechamiento de un edificio (las demás siguen).",
  "log.object_uninstalled": "Se desinstaló un objeto entero.",
  "log.object_installed": "Se instaló un objeto.",

  "resource.piping": "Tuberías",
  "resource.glass": "Vidrio",
  "resource.ceramics": "Cerámica (sanitarios, baldosas, azulejos)",
  "resource.masonry": "Mampostería (ladrillo, bloque, piedra)",
  "resource.roof_tiles": "Tejas",
  "resource.structural_steel": "Acero estructural (perfiles, ferralla)",
  "resource.rubble": "Escombros",

  "installation.electricity": "Instalación eléctrica",
  "installation.water": "Instalación de agua",
  "installation.hot_water": "Agua caliente sanitaria",
  "installation.heating": "Calefacción",
  "installation.telecom": "Telecomunicaciones",
  "installation.ventilation": "Ventilación",
  "finish.window": "Ventana",
  "finish.shutters": "Persiana",
  "finish.sanitary_ware": "Sanitarios",
  "finish.kitchen_units": "Muebles de cocina",
  "finish.countertop": "Encimera",
  "finish.wood_flooring": "Parquet/tarima",
  "finish.floor_tiles": "Baldosas",
  "finish.wall_tiles": "Azulejos",
  "finish.insulation": "Aislamiento",
  "finish.railing": "Barandilla",
  "target.opening.exterior": "Acceso exterior",
  "target.opening.interior": "Puerta interior",
  "target.building": "Edificio",
  "access.side.exterior": "exterior",
  "access.width.narrow": "estrecho",
  "access.width.normal": "normal",
  "access.width.wide": "ancho",
  "access.width.gate": "portón",
  "closure_state.open": "abierto",
  "closure_state.closed": "cerrado",
  "closure_state.locked": "bloqueado",
  "closure_state.destroyed": "destruido",
  "closure_state.none": "sin cierre (hueco)",
  "obstruction.blockade": "barricada",
  "obstruction.boarded_up": "tapiado",
  "obstruction.rubble": "escombros",
  "obstruction.furniture_block": "mueble bloqueando",
  "destination.install_at_opening": "Instalar en una abertura sin cierre",
  "destination.install_at_place": "Instalar en la fuente de agua",

  "layer.loose_content": "1. Contenido suelto",
  "layer.furnishings": "2. Mobiliario y equipamiento",
  "layer.installations": "3. Instalaciones",
  "layer.finishes": "4. Acabados",
  "layer.structure": "5. Estructura",
  "layer_knowledge.unknown": "desconocido",
  "layer_knowledge.recognized": "reconocido",
  "layer_knowledge.explored": "explorado",
  "layer_knowledge.partially_registered": "registrado en parte",
  "layer_knowledge.registered": "registrado",
  "layer_knowledge.specialist_registered": "registrado por especialista",
  "layer_physical.intact": "intacta",
  "layer_physical.partially_exploited": "explotada en parte",
  "layer_physical.exhausted": "agotada",
  "layer_physical.destroyed": "destruida",
  "layer_physical.unavailable": "no disponible en esta partida",
  "exploitation_stage.unknown": "Desconocido",
  "exploitation_stage.recognized": "Reconocido",
  "exploitation_stage.explored": "Explorado",
  "exploitation_stage.registered": "Registrado",
  "exploitation_stage.specialist_registered": "Registrado por especialista",
  "exploitation_stage.emptied": "Vaciado de contenido suelto (quedan mobiliario, instalaciones, acabados y estructura)",
  "exploitation_stage.dismantling": "Desmontando (segunda vida en curso)",
  "exploitation_stage.dismantled": "Desmantelado",
  "exploitation_stage.demolished": "Demolido",
  "life_stage.first_life": "Primera vida (saqueo)",
  "life_stage.second_life": "Segunda vida (desmontaje)",
  "life_stage.third_life": "Tercera vida (desmantelamiento)",
  "life_stage.terminal": "Ya no existe como edificio",
  "era.old": "Construcción antigua",
  "era.modern": "Construcción moderna",
  "habitability.habitable": "Habitable",
  "habitability.precarious": "Precario",
  "habitability.uninhabitable": "Inhabitable",
  "habitability.inaccessible": "Sin acceso utilizable",
  "habitability.demolished": "Demolido (sin habitabilidad)",
  "habitability.factor.demolished": "Demolido.",
  "habitability.factor.dismantled": "Desmantelado.",
  "habitability.factor.structure_partially_dismantled": "Estructura parcialmente desmantelada.",
  "habitability.factor.damaged_structure": "Estructura dañada.",
  "habitability.factor.exposed_accesses": "Accesos exteriores sin cierre (expuesto).",
  "habitability.factor.finishes_recovered": "Acabados retirados.",
  "habitability.factor.windows_removed": "Ventanas retiradas (estancias expuestas).",
  "habitability.factor.installations_removed": "Instalaciones desmontadas.",
  "habitability.factor.no_rest_support": "Sin soporte de descanso.",
  "habitability.factor.no_usable_access": "Ningún acceso utilizable: no se puede entrar.",
  "preview.irreversible": "Irreversible: no existe ninguna acción que lo deshaga.",
  "preview.dismantle.slow_by_stages": "Lento, por etapas (cubierta, cerramientos, muros, cimentación).",
  "preview.dismantle.requires_emptied": "Exige sacar antes todo el contenido y el mobiliario.",
  "preview.dismantle.recovers_reusable": "Recupera más material reutilizable (vigas, ladrillo, teja, perfiles) y menos escombro.",
  "preview.dismantle.loses_remaining_fixtures": "Las instalaciones y acabados que sigan montados se perderán al terminar.",
  "preview.demolish.fast": "Rápido.",
  "preview.demolish.destroys_everything_inside": "Destruye todo lo que quede dentro: contenido, mobiliario, instalaciones, acabados y cierres.",
  "preview.demolish.mass_materials_and_rubble": "Deja materiales masivos de baja calidad y muchos escombros.",
  "preview.demolish.ends_building": "El edificio deja de existir: sin alojamiento, almacén, defensa ni taller.",

  // Necesidades (etiquetas y bandas cualitativas).
  "need.hydration": "Hidratación",
  "need.nutrition": "Nutrición",
  "need.rest": "Descanso",
  "need.band.stable": "Estable",
  "need.band.in_need": "Con necesidad",
  "need.band.urgent": "Urgente",
  "need.band.critical": "Crítica",
};

export function copyKey(key: string | null | undefined): string {
  if (!key) return "";
  return COPY_KEYS[key] ?? key;
}
